### ISSUE TITLE
Multiple M3U list

### ISSUE THREAD

**Issue by daxime** [Fredolx/open-tv#14]
Hello,
I will be great to have multiple M3U list to switch easily between them, instead of having to delete one list to add another.

**Comment by Fredolx** [comment]
I will work on this once I finish xtream support

**Comment by daxime** [comment]
Ok, Thx :)

**Comment by kalermo** [comment]
Hi, any progress with this one? Would be perfect to have this option.

**Comment by Fredolx** [comment]
It's done. Thank you
