### ISSUE TITLE
Can't login with Xtream

### ISSUE THREAD

**Issue by padraig333** [Fredolx/open-tv#15]
Tried logging with my Xtream Playlist but it says 'Invalid URL or credentials' I checked and they are right my playlist has both streams and VODs so would that play a part? Thanks for response!

**Comment by Fredolx** [comment]
Thank you for your feedback. I may already have fixed this issue in one of the recent commits I made to master that didn't land on a release yet. You could help me by trying out [this build](https://github.com/Fredolx/open-tv/actions/runs/4570981739). Just pick the proper artifact for your operating system.

**Comment by padraig333** [comment]
It is working perfectly. Logged in fine, turns out it wasn't pointing to a Xtream server as it put it. Streams worked, VODs worked. Very satisfied! Thanks for reply
