### ISSUE TITLE
Xtreme login issue

### ISSUE THREAD

**Issue by James1o1o** [Fredolx/open-tv#20]
Hi,

I saw there was a similar problem on a closed issue, I believe your fix in that thread has been moved into the current release?

I've having similar problems logging in, I've used a few applications today, so I know my details and info are correct. 

My server actually has a https protocol instead of http? I'm not sure if that's unusual or maybe causing some issues? Each time I try to login with it, it's automatically adding http to an already https URL.

eg: "http://https://xxxxx.ddns.net:8443"

If you privately message me I can happily give you the server info to see if you can try suss out what is causing my login issue.

**Comment by Fredolx** [comment]
Hi James. Yes if you can fill me in with some extra details in private I'd be glad to look into this.

Thank you!

**Comment by James1o1o** [comment]
Hi mate sorry, I don't know how to message on Github, 

If you use reddit, could you possibly message me on there?

https://www.reddit.com/u/james1o1o

**Comment by James1o1o** [comment]
Have sent you the messsage, hopefully helps to diagnose the issue!

**Comment by Fredolx** [comment]
It will be fixed in the next release. Thank you!
