### ISSUE TITLE
Cannot play media on MacOS, M1

### ISSUE THREAD

**Issue by sinanacar** [Fredolx/open-tv#21]
I've installed all needed dependencies but no luck; playing a channel or VOD is not possible with MacOS on M1 platform. Clicking a channel brings nothing.

**Comment by Fredolx** [comment]
Hi,

Sorry for the delay. So you have mpv installed through homebrew or macports?
What is your MacOS version?

Contact me by email at frederic.lachapelle7@gmail.com if you would like to share your m3u/xtream logins so I could investigate further. Thank you

**Comment by sinanacar** [comment]
I'm indeed sorry for the delay. Thank you for your reply.

I've installed mpv via homebrew; on Ventura 13.2.1.

Sure, I'll send out an e-mail to you in a few. Thanks a bunch again.

**Comment by mebsout** [comment]
I have the same issue but it works if I launch open tv with `/Applications/Open\ TV.app/Contents/MacOS/open-tv`.

**Comment by felle64** [comment]
when trying to play i get: Waiting for mpv start
Error occurred in handler for 'playChannel': 127
both on my M1 Pro and my Hackintosh

**Comment by Fredolx** [comment]
If the new version doesn't fix this, please re-open.

**Comment by Fredolx** [comment]
I will investigate this. I'm probably going to allow mpv-compatible players like IINA

**Comment by Fredolx** [comment]
I fixed the issue. The fix will be available with 1.0.2. For IINA, unfortunately they removed some features from mpv that makes it suitable for IPTV so it will not be added. If IINA adds yt-dlp support, I will make it available.

**Comment by vordenken** [comment]
IINA has yt-dl support, is this enough? (Can be found under settings - network)

**Comment by Fredolx** [comment]
It's fixed with 1.0.2. Thanks for the issue.
