### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by cat-marin** [Fredolx/open-tv#22]
Would you consider putting this on flathub? If you don't want to that's cool, but I didn't see any requests so I figured I would ask.

**Comment by Fredolx** [comment]
I will release a flatpak this week as we are finally reaching 1.0

**Comment by Fredolx** [comment]
I'm a bit overwhelmed, if you have experience with flatpak I would appreciate if you or someone else contribute a manifest.

**Comment by Fredolx** [comment]
I've done the manifest and it will be published to flathub
