### ISSUE TITLE
allow use of custom mpv config

### ISSUE THREAD

**Issue by hacktek** [Fredolx/open-tv#24]
Hello, similar to what was mentioned here: https://github.com/Fredolx/open-tv/issues/13

I would like to be able to specify an mpv config file that overrides some options. This would allow for much greater personalization, for instance I want my videos to start at a specific size and with float on top enabled as I prefer that to defaulting to full screen, the config file would allow me to do that.

Or alternatively, allow to use mpv options such as `--ontop`

**Comment by Fredolx** [comment]
I agree, I wanted to implement this a while ago but I've been busy; I've been thinking of implementing per-channel and global mpv/yt-dlp configs. We'll see. Thank you!

**Comment by Fredolx** [comment]
I had some spare time tonight and implemented the feature: I made it possible to have a custom mpv config for all channels. For per-channel settings, I'll have to see how I want to implement it. 

Issue closed by da3d06bb24fa7f3f44289457d76917b52907997c
Thank you!
