### ISSUE TITLE
Issue Playing

### ISSUE THREAD

**Issue by SteffanCaine** [Fredolx/open-tv#29]
Hi,

First of all thanks a lot for this app, I've been using it without issue for a while and it's fantastic. Unfortunately when I've set it up again via xstream, I can't seem to play any channel. Is there a log I could check for further info?

I've checked the login in a different app and it's working well, the channel list is fully retrieved so it's not a credential issue. 

The url I've been provided is https://example.com but I can only add the account by removing protocol as it detects no protocol and then auto changes the url to http://https://example.com which of course doesn't work. The only way to add it successfully is with no protocol and then accepting the prompt to fix the url automatically, this could be part of the problem so I thought I'd mention it.

Thanks again

**Comment by Fredolx** [comment]
No problem, providers are indeed often the source of the issue with that. Have a nice day.
