### ISSUE TITLE
openSUSE binary support

### ISSUE THREAD

**Issue by petrusd10s** [Fredolx/open-tv#31]
The generic linux tarball of the application can be used without issues on openSUSE (after installing electron packages) (I only tried Tumbleweed), and I thought that it could be a great idea to have this project on the Open Build Service

https://build.opensuse.org/

Pretty much like how the AUR works

**Comment by Fredolx** [comment]
I made the aur package, but I have never tried making packages for the OBS. I'll look it up. I had intentions to re-rewrite the app in Rust for better linux compatibility (because everyone hates Electron on Linux) where I would add flatpak support at the same time
