### ISSUE TITLE
Multiple Xtreams

### ISSUE THREAD

**Issue by nazimdz212121** [Fredolx/open-tv#35]
It's would be great if we could add multiple xtreams and switch between them :)
Great app btw

**Comment by Fredolx** [comment]
I appreciate the feedback. I am currently re-writing the app in Rust to make this feature possible

**Comment by cinaroglu** [comment]
I'm just here to say thank you to Fredolx for making this great app for Windows. Keep up the good work brother! There's no any better app than this!

**Comment by Fredolx** [comment]
It's done. Thank you for kind comments and the suggestion.
