### ISSUE TITLE
Cannot parse m3u file

### ISSUE THREAD

**Issue by ttx99** [Fredolx/open-tv#42]
got the m3u file here https://github.com/dtankdempse/thetvapp-m3u

https://bit.ly/tta-m3u

it cant parse the downloaded m3u file

**Comment by Fredolx** [comment]
I'll look into it today. Thanks for making the issue

**Comment by Fredolx** [comment]
The file provided doesn't follow m3u format properly, this is why it fails to process. If you want to test, this list is valid
https://github.com/iptv-org/iptv
