### ISSUE TITLE
(Request) Updater

### ISSUE THREAD

**Issue by cinaroglu** [Fredolx/open-tv#43]
Hello,

Firstly I just wanted to thank you for this great work. And I have a question and a kindly request. Why don't you add an updater for further versions of Open TV? 

This way we need to check github for newer versions and reinstall it. 

Also, for movie/series categories, it does not show categories that I normally have on my IPTV. Is there any chance to add that feature in the future? Thank you!!!

**Comment by cinaroglu** [comment]
My bad- 

It shows categories for movies/series but when we choose not to see livestreams, still it shows livestream categories on categories tab. Not only series/movies.

**Comment by Fredolx** [comment]
That's a good question; the app is getting released on both Flathub and Microsoft Store where automatic updates will be available. It should be up on Flathub in the next few days, no ETA for Microsoft Store but it's being reviewed by Microsoft as we speak.

**Comment by Fredolx** [comment]
> My bad- 
> 
> It shows categories for movies/series but when we choose not to see livestreams, still it shows livestream categories on categories tab. Not only series/movies.

I'll look into this. Thank you

**Comment by cinaroglu** [comment]
Deleted free version and I bought in on Microsoft Store. Keep up the good work brother

**Comment by Fredolx** [comment]
Thank you for your support
