### ISSUE TITLE
player dont display the channel name

### ISSUE THREAD

**Issue by ttx99** [Fredolx/open-tv#45]
from https://github.com/dtankdempse/free-iptv-channels

Samsung tv plus m3u
https://tinyurl.com/multiservice21?region=us&service=SamsungTVPlus

also pluto and ans stirr and probably every service the channel names are just numbers

**Comment by Fredolx** [comment]
are you on Windows or Linux? If on linux, do you use the flatpak?

**Comment by ttx99** [comment]
windows

**Comment by ttx99** [comment]
v.1.1 still the same doesnt display channel name properly and now m3u url like this https://bit.ly/tta-m3u

 wont not fetch in v1.0 works

**Comment by Fredolx** [comment]
Title is added on 1.0.2
