### ISSUE TITLE
Failed to fetch series

### ISSUE THREAD

**Issue by a-hersa** [Fredolx/open-tv#46]
Hello,

An error 'Failed to fetch series' appears when trying to open any series.
This happens on Windows, version 1.0.0

**Comment by Fredolx** [comment]
Thank you for making this issue. I will be looking into this. If you don't mind, you can send me your xtream info to frederic.lachapelle7@gmail.com so I can fix the issue fadter.

**Comment by Fredolx** [comment]
Should be fixed with 1.0.3
