### ISSUE TITLE
Add error checking when channels cannot be played

### ISSUE THREAD

**Issue by lgaudreau** [Fredolx/open-tv#48]
This is a great app, thanks!  

One thing I found - I launched the app and imported a playlist of channels.  Trying to open many of the channels resulted in nothing happening in the interface at all beyond the channel button click, even after waiting in case it was due to network buffering.  In the console, the flatpak app shows the stream playing:

```
flatpak run dev.fredol.open-tv
https://<redacted - not sure about posting IPTV Links here>.m3u8 playing
```

When I open the playlist in VLC (changing channels using the 'next' and 'back' buttons), it gives me an error for the channels I'm not able to open in open-tv:

`VLC is unable to open the MRL`

In the VLC log the following error appears:

```
access error: HTTP 403 error
http error: local stream 1 error: Cancellation (0x8)
```

The reason open-tv can't open them is from the URL being blocked in Canada, but open-tv only shows 'playing' and not that there is any issue with the URL or stream.

Sorry this isn't very technical, but hopefully it's helpful.

**Comment by Fredolx** [comment]
I think it's a great idea, I will be working on this for 1.0.2

**Comment by Fredolx** [comment]
Thanks for the issue, it's been added for 1.0.2
