### ISSUE TITLE
v1.0.1 aarch64 dmg: "damaged" app

### ISSUE THREAD

**Issue by elsbrock** [Fredolx/open-tv#51]
I can't get the v1.0.1 aarch64 version on my M1 working. Copying the app is working fine, but starting fails with "Open TV.app is damaged and can't be opened".

**Comment by Fredolx** [comment]
I'm aware of this, the fix will be available for 1.0.2.

Thank you

**Comment by Fredolx** [comment]
I'll keep this issue open until 1.0.2 is released to avoid duplicates. Thank you for creating the issue

**Comment by Fredolx** [comment]
Fixed. Thanks for the issue.
