### ISSUE TITLE
watch history 

### ISSUE THREAD

**Issue by larcn** [Fredolx/open-tv#52]
It's not an issue, but I have a request. Could you please add a watch history feature? The program already remembers the file position, which is great, but it would be perfect if it also remembered the last show/episode we watched .. many thanks for your work

**Comment by Fredolx** [comment]
That sounds like a nice idea

**Comment by Fredolx** [comment]
I will make this happen for 1.0.3. Thanks for the idea.

**Comment by larcn** [comment]
Many thanks , also I sent email with attachments about the xtream problem , hope u can solve it

**Comment by Fredolx** [comment]
The feature will be delayed. I will re-open this issue when I come around it.
