### ISSUE TITLE
Channels not found

### ISSUE THREAD

**Issue by mrsanor** [Fredolx/open-tv#53]
I am trying to add an M3U playlist via URL/file. The playlist is succesfully added but Open TV remains empty. I have tried uninstalling and reinstalling and removed some cached files I found from AppData/Roaming/fredol but nothing works. Everything works with other IPTV players. 

![image](https://github.com/user-attachments/assets/e73c4635-d2e8-4075-9693-b423301246c5)

Also Xtream link is giving this error and don't work. It works with other players.

![image](https://github.com/user-attachments/assets/9b12a8e7-13ea-4aef-905a-b7b1339b4197)

I am using Windows 11 Pro x64 and tried both version 1.0.0 and 1.0.1.

Version 1.0.0 worked for me once but after computer restart it hasn't worked since.

**Comment by Fredolx** [comment]
Re-open if the bug still occurs on latest release.
