### ISSUE TITLE
Enhancement: Make Favorites the default tab when opening Open-TV?

### ISSUE THREAD

**Issue by archfrog** [Fredolx/open-tv#56]
Thanks for a great app.

I have one tiny suggestion.  I'd like to see the Favorites tab being the default (opened) tab when you open the app.  Because I have thousands of IPTV channels in my All tab and perhaps 50-100 categories in the Category tab.  I'm using the list from [GitHub: IPTV](https://github.com/iptv-org/iptv), because I want to gradually search for more channels as time permits.

In fact, I'd suggest that you reorder the tabs so they are: Favorites, Categories, and then All.  I think that most users will be using the Favorites tab more than the others.  I'm not sure this is an awesome idea, though, as I have no idea what other users of the app prefer.

P.S. I gave a thumbs up to the suggestion that the app should report an error when it cannot open a channel.  I'm watching a 24-hour channel, but very often, it appears that it is not up even though it is supposed to be.

**Comment by Fredolx** [comment]
Thanks for the suggestion. I will make it happen for 1.0.3

**Comment by Fredolx** [comment]
This has been added to master (scheduled to be released for 1.0.3). Tell me what you think. Also the error reporting has been vastly improved on the newly released 1.0.2

https://github.com/user-attachments/assets/026fbb99-cd11-48a5-a7ec-109039f6c633

**Comment by archfrog** [comment]
Thank you!

I've installed v1.02 and it looks good with the new error reporting.  I'll install v1.03 as soon as you release it.

I'd like to support you so I am going to use GitHub to sponsor you one time for now.  I don't do bitcoins and I won't buy the Microsoft Store app because it requires me to sign in with my Microsoft Account on Windows, something I don't want to do.

**Comment by archfrog** [comment]
Took a while before I realized you had attached a video of the new change :-)  It looks very good, thanks.

I have sponsored you with $25 :-)

**Comment by Fredolx** [comment]
The feature has been added with 1.0.3. Thank you for your support.
