### ISSUE TITLE
Enhancement: Remember volume level across app invocations

### ISSUE THREAD

**Issue by archfrog** [Fredolx/open-tv#57]
It seems the app does not save the last volume level the user configured (using mouse-wheel up and down).  It would be nice if the app remembered the last volume across app launches :-)

**Comment by archfrog** [comment]
I just realized that the app is using MPV as an external player and hence it is probably not easy to save the volume level.

Perhaps you can pass an argument to MPV with the volume level?  On my system, it appears the audio level is 100 percent when any channel starts playing, which is sort of too loud for all channels.  Perhaps 66 percent would be better?

This is nothing critical, just a nice to have.

**Comment by Fredolx** [comment]
I'm not sure this is possible on all medias, it seems MPV only allows you to remember it for the last file/link.
What I would suggest for your use-case is to set --volume=66 in the MPV options in the app.
<img width="798" alt="Screenshot 2024-10-17 at 11 18 35 AM" src="https://github.com/user-attachments/assets/b5a59cb0-812e-4f75-9197-039e21ae3b62">

**Comment by archfrog** [comment]
Thank you, that's perfect!  Now I don't have to turn down the volume every time I open a channel.

**Comment by Fredolx** [comment]
No problem. I might still add a volume slider in the settings (that would do essentially the same thing as --volume) so that other people  don't have to figure that out. 

Thank you for the suggestion.

**Comment by Fredolx** [comment]
The volume slider has been added with 1.0.3
