### ISSUE TITLE
Enhancement: save and transfer favorite 

### ISSUE THREAD

**Issue by larcn** [Fredolx/open-tv#58]
can we transfer favorite between 0.9 to 1.0

**Comment by Fredolx** [comment]
I could add a button in settings to import favs before 1.0.0. Might make it for 1.0.3

**Comment by larcn** [comment]
> I could add a button in settings to import favs before 1.0.0. Might make it for 1.0.3

Many thanks

**Comment by Fredolx** [comment]
I'm delaying this feature for now. Sorry. I will re-open when I get more time.
