### ISSUE TITLE
User video folder hardcoded

### ISSUE THREAD

**Issue by Arsconyl** [Fredolx/open-tv#6]
First, I want to thank you for this app. It is miles better compared to use VLC for IPTV.

I think that there is a path that is hardcoded in the app:
![image](https://user-images.githubusercontent.com/28065660/226738391-f8d8817e-e408-44c9-9856-621e819230df.png)

Creating the folder C:\User\\{USER}\Videos resolves the issue.

**Comment by Fredolx** [comment]
I'll look into this, thank you

**Comment by Fredolx** [comment]
Fixed by dd120aa
