### ISSUE TITLE
1.0.2 error

### ISSUE THREAD

**Issue by larcn** [Fredolx/open-tv#60]
related to closed issues 40
installed ver 1.0.2 now .. when i try to open some category i get this error
        Wrong number of parameters passed to query. Got 6, needed 8
=
another error
        error decoding response body

Caused by:
    invalid length 0, expected struct XtreamEpisodeInfo with 1 element at line 1 column 406875
    =
and some category show blank without error

**Comment by Fredolx** [comment]
could you record a video or take a screenshot of the error when you open a category? Thank you

**Comment by larcn** [comment]
> could you record a video or take a screenshot of the error when you open a category? Thank you

Thanks for reply , I sent 2 for u a few day ago for the new ver vs old one and other iptv player.. want me to record new one or longer ?

**Comment by larcn** [comment]
https://github.com/user-attachments/assets/5509e142-1bbb-4424-80d0-f96f1a185d9e

as u can see sometime i show category inside each other

**Comment by Fredolx** [comment]
Are those series? Do you only get the error when accessing them from favorites?

Thank you

**Comment by larcn** [comment]
> Are those series? Do you only get the error when accessing them from favorites?
> 
> Thank you

yes they are 
no , from search , from category also .. also not all category show error

https://github.com/user-attachments/assets/73415d3e-6cbb-4483-9494-44a57c8b8c28

**Comment by Fredolx** [comment]
Thanks for the videos. I was able to identify the bugs and correct them. The fix will be available with 1.0.3

**Comment by betov69** [comment]
Hello, I have the same error, but in my cases it only happens with the search for the series, the movies work fine, greetings

**Comment by Fredolx** [comment]
Hi guys,
I've been working on this issue today and I've fixed all of the bugs related to series.
All fixes will be available with 1.0.3

**Comment by Fredolx** [comment]
Should be fixed. Please use the "Delete everything" button if you're still having trouble
