### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by steinxborg** [Fredolx/open-tv#67]
Error:
     `Too many problematic lines, read considered failed`
     
Below are the contents of the m3u8 file. It seems you do not support custom headers?
```
#EXTM3U

#EXTINF:-1 tvg-logo="https://sportslive.me/wp-content/uploads/2024/09/favicon.png" tvg-id="A&E USA",A&E USA
#EXTVLCOPT:http-referrer=https://faptok.site/sportslive/pl1.php?play=302
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
https://faptok.site/sportslive/stream.m3u8?id=302
```

Open TV(v1.0.3)

**Comment by Fredolx** [comment]
are the referrer and user agent necessary to play this channel?

I typically discard those custom headers but I didn't know you could have more than one line of those per channel

**Comment by Fredolx** [comment]
Ok, great, I'll be adding the parsing of those headers to Open TV.

**Comment by Fredolx** [comment]
I started working on this. It should be ready today. If you want to test the experimental build, it would be greatly appreciated; please let me know your OS. Thank you

**Comment by stein-dev** [comment]
I am using ubuntu. I'm available for testing.

**Comment by truehat** [comment]
I would also be down to test.

**Comment by Fredolx** [comment]
This feature has been added with v1.1.0. Thank you for making the issue.
