### ISSUE TITLE
Arch

### ISSUE THREAD

**Issue by daxime** [Fredolx/open-tv#7]
Hi,
Is it possible to have an Appimage or a way to install on Manjaro?

**Comment by Fredolx** [comment]
AppImage is not supported by my build tools unfortunately. It is possible to run on Arch, but no way to install. I will attempt to make a pkgbuild and publish it on the aur soon.

**Comment by daxime** [comment]
I tried to compile it, but it's not really in my area of expertise, so it didn't work.
I tried to convert the .deb to be compatible with Arch, the converter I found seemed to work, but there is a dependency problem... 

I'll wait for an Arch package

**Comment by ADHDefy** [comment]
@Fredolx Would Flatpak be possible? It would be really convenient for Fedora users, but I believe basically any distro can use Flatpak, as well.

**Comment by Fredolx** [comment]
> @Fredolx Would Flatpak be possible? It would be really convenient for Fedora users, but I believe basically any distro can use Flatpak, as well.

Yes a flatpak is possible. I will publish one soon.

**Comment by Fredolx** [comment]
Ok so I've done the work and now Open TV is on the aur!

https://aur.archlinux.org/packages/open-tv-bin

Have fun

**Comment by daxime** [comment]
Great Thx :)
