### ISSUE TITLE
Windows Store version

### ISSUE THREAD

**Issue by sheam** [Fredolx/open-tv#71]
How long does it take for the latest release to make it to the Windows Store? The store shows _Release Date_ but not the actual version.

**Comment by Fredolx** [comment]
Generally it takes about 3 hours. Thank you for supporting Open TV!

**Comment by sheam** [comment]
It is showing last version ast Oct 8th. But I see there are newer releases
on gihub here. Just wondering if I go with windows store if I will get
latest updates. Thanks.

**Comment by Fredolx** [comment]
The Microsoft Store always has the lastest update first. Sometimes the date on the listing is wrong, but I can assure you it's on the latest version.
