### ISSUE TITLE
Allow editing of user/pass

### ISSUE THREAD

**Issue by gtxaspec** [Fredolx/open-tv#72]
currently you have to delete the whole profile (xtream) and recreate.  editing the username and password would be a fine addition.

**Comment by larcn** [comment]
And maybe mask user/pass in logs 
U have xtream acc?

**Comment by Fredolx** [comment]
It's a good idea but I want to keep Open TV as simple as possible. Won't be doing it for now.

**Comment by gtxaspec** [comment]
This feels like a very basic feature. Without it, users are forced to delete the profile and re-add it just to update credentials, which may be required by the provider every few days. While simplicity is important, omitting this feature detracts from the otherwise wonderful usability of the program. It's hard to see a use case where adding it wouldn't be beneficial.

**Comment by Fredolx** [comment]
I didn't know some providers change their user pass that often. In that case, I'll reopen this issue.

**Comment by Fredolx** [comment]
https://github.com/user-attachments/assets/658a42fc-38df-46a9-b9b7-f3446331ced7

**Comment by Fredolx** [comment]
https://github.com/Fredolx/open-tv/pull/87

**Comment by Fredolx** [comment]
PR Merged. Will be released along with update 1.2.0 (ETA: 3 days)

**Comment by Fredolx** [comment]
Added with 1.2.0
