### ISSUE TITLE
V1.00 was able to parse this

### ISSUE THREAD

**Issue by ttx99** [Fredolx/open-tv#74]
pls refer to this https://github.com/dtankdempse/thetvapp-m3u 
v1 was able to parse this

**Comment by Fredolx** [comment]
I'll look into this, thank you

**Comment by ttx99** [comment]
[2024-12-09-01-12-11.log](https://github.com/user-attachments/files/18053287/2024-12-09-01-12-11.log)

**Comment by Fredolx** [comment]
Amazing, the log will help

**Comment by Fredolx** [comment]
It will be fixed with next update

**Comment by Fredolx** [comment]
Should be fixed with 1.2.0. Re-open if it's not the case
