### ISSUE TITLE
Can't open m3u file

### ISSUE THREAD

**Issue by jamexcb** [Fredolx/open-tv#78]
I'm using version 1.0.3
**Error:** 
Too many problematic lines, read considered failed

**This is just some lines from the log:**
18:58:57 [ERROR] Failed to process lines #1 #2, skipping

Caused by:
    Couldn't find name from Name or ID
18:58:57 [ERROR] Failed to process lines #3 #4, skipping

Caused by:
    Couldn't find name from Name or ID
18:58:57 [ERROR] Failed to process lines #5 #6, skipping

**This is the url of m3u:**
https://raw.githubusercontent.com/LITUATUI/M3UPT/main/M3U/M3UPT.m3u

**This is part of the m3u file:**
#EXTM3U url-tvg="https://github.com/LITUATUI/M3UPT/raw/main/EPG/epg-nos-pt.xml.xz,https://github.com/LITUATUI/M3UPT/raw/main/EPG/epg-meo-pt.xml.xz,https://github.com/LITUATUI/M3UPT/raw/main/EPG/epg-rtp-pt.xml.xz,https://github.com/LITUATUI/M3UPT/raw/main/EPG/epg-rytec-pt.xml.xz"

# M3UPT.com - IPTV playlist in M3U format with 📺 TV channels and 📻 radio stations in 🇵🇹 Portuguese. Public and official streams only.

# 📺 TV

#EXTINF:-1 group-title="TV" tvg-id="RTP1.pt" tvg-logo="https://raw.githubusercontent.com/LITUATUI/M3UPT/main/logos/RTP1.png",RTP 1
#EXTVLCOPT:http-user-agent=Firefox
https://streaming-live.rtp.pt/liverepeater/smil:rtp1HD.smil/playlist.m3u8

#EXTINF:-1 group-title="TV" tvg-id="RTP2.pt" tvg-logo="https://raw.githubusercontent.com/LITUATUI/M3UPT/main/logos/RTP2.png",RTP 2
#EXTVLCOPT:http-user-agent=Firefox
https://streaming-live.rtp.pt/liverepeater/smil:rtp2HD.smil/playlist.m3u8

**Comment by Fredolx** [comment]
the format of this file is all wrong, won't be supported.

**Comment by jamexcb** [comment]
Ok thanks for the feedback. But it's supported by: https://codeberg.org/liya/yuki-iptv and other non open source players. Maybe this can be a feature requeste for the future. Thanks

**Comment by Fredolx** [comment]
I'll look into it, this is actually the 2nd m3u I see like this so I'm going to try to support it

**Comment by Fredolx** [comment]
This will be fixed for the next update

**Comment by jamexcb** [comment]
Wow! Thanks I will test and give you feedback.

**Comment by Fredolx** [comment]
Should be fixed with 1.2.0. Re-open if it's not the case

**Comment by jamexcb** [comment]
File opens OK. But has other issues not related with m3u file. I will open a different issue.
Thanks :)
