### ISSUE TITLE
streams closing without error

### ISSUE THREAD

**Issue by antopio** [Fredolx/open-tv#79]
Hi, the app is great, but very frequently a stream will just close and I have to manually reopen it. 

Also, I'm unable to open multiple streams at the same time. When I open a second, the first one will always close.

It almost seems to occur instead of buffering. Any advice on how I can fix this?

**Comment by larcn** [comment]
ver?

**Comment by antopio** [comment]
> ver?

v1.0.3, from the microsoft store. running on win 11

**Comment by antopio** [comment]
@Fredolx any support on this?

**Comment by larcn** [comment]
last ver have some issues , i moved back to 0.9.8 .. also u can see on activity he is working hard

**Comment by TejS40** [comment]
I'm having the same issues about the streams randomly closing, same version

**Comment by Fredolx** [comment]
Hi guys, just to confirm with everyone who has been having this issue, does reverting to 0.9.8 really fixed it?

**Comment by antopio** [comment]
same here. i can have multiple streams open, nothing closes, no crashing

**Comment by Fredolx** [comment]
Are you guys using the stream caching option set to off in 0.9.8?

**Comment by Fredolx** [comment]
Can someone having this issue run the latest version and try adding the following to their Global MPV Parameters:
```
--prefetch-playlist=yes --loop-playlist=inf
```
Report back if there was an improvement. Thank you

**Comment by Fredolx** [comment]
> > Can someone having this issue run the latest version and try adding the following to their Global MPV Parameters:
> > 
> > ```
> > --prefetch-playlist=yes --loop-playlist=inf
> > ```
> > 
> > Report back if there was an improvement. Thank you
> 
> How I can backup and save 0.9.8 favorite? , i can try to install i but want o make sure my old data will be save 
> 

You can check, on Windows, your %appdata% folder or %localappdata% there should be a fredol or opentv folder in there. Then there should be a favs file in here. You can backup that file or the entire folder

**Comment by antopio** [comment]
> > > Can someone having this issue run the latest version and try adding the following to their Global MPV Parameters:
> > > ```
> > > --prefetch-playlist=yes --loop-playlist=inf
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Report back if there was an improvement. Thank you
> > 
> > 
> > How I can backup and save 0.9.8 favorite? , i can try to install i but want o make sure my old data will be save
> 
> You can check, on Windows, your %appdata% folder or %localappdata% there should be a fredol or opentv folder in there. Then there should be a favs file in here. You can backup that file or the entire folder

the newest version seems to work for me as well with these options. i didn't test for very long though

**Comment by TejS40** [comment]
> Can someone having this issue run the latest version and try adding the following to their Global MPV Parameters:
> 
> ```
> --prefetch-playlist=yes --loop-playlist=inf
> ```
> 
> Report back if there was an improvement. Thank you

I've been trying it with these options on the latest version. So far, so good.

**Comment by Fredolx** [comment]
Thanks for the feedback guys. It will be part of the next update.

**Comment by Fredolx** [comment]
fixed with v1.1.0. Thank you
