### ISSUE TITLE
Incorrect channel name when using tvheadend m3u files

### ISSUE THREAD

**Issue by adriadam10** [Fredolx/open-tv#80]
Hi, first of all, nice app! simple and easy to use.

I have tried to add my m3u from [tvheadend](https://github.com/tvheadend/tvheadend) but it gets the channels with an incorrect name.
It seems that it extracts the name from a variable called tvg-id that appears in the line of the channel inside the m3u.

Here's is the scheme that every channel follows:
`#EXTINF:-1 tvg-logo="logo-link" tvg-id="random-id",Channel_name stream-link`

**Comment by Fredolx** [comment]
Hi :)
I'll be adding support for this format.
Also, just to be clear, the stream-link in your format is on the same line? There is no \n (newline)?

**Comment by Fredolx** [comment]
fixed with v1.1.0. Thank you

**Comment by lukefor** [comment]
This is still broken as of 1.4.1
