### ISSUE TITLE
The home screen should display the channel Name rather than channel ID

### ISSUE THREAD

**Issue by suokunlong** [Fredolx/open-tv#82]
For instance, we have the following m3u definitions:

```
#EXTINF:-1 tvg-id="FoxNewsNow", FOX News Now
https://fox-foxnewsnow-samsungus.amagi.tv/playlist.m3u8
#EXTINF:-1 tvg-id="FoxBusiness", FOX Business
http://41.205.93.154/FOXBUSINESS/index.m3u8
```
On the UI, the list of channels are displayed as "FoxNewsNow" and "FoxBusiness".
It is expected that the names "FOX News Now" and "FOX Business" are shown in the channel list.

**Comment by Fredolx** [comment]
fixed with v1.1.0. Thank you
