### ISSUE TITLE
there should be 3 categories, live, video and series 

### ISSUE THREAD

**Issue by farhanffaa** [Fredolx/open-tv#83]
I suggest the following enhancements to improve the user experience:

Button Navigation:
Replace the current toggles with dedicated buttons for Live, Movies, and Series. This would allow users to click directly on a category (e.g., Movies) to view all associated subcategories or services, streamlining navigation.

Enhanced Search Functionality:
Refine the search bar to enable filtering by specific categories (Live, Movies, or Series). Currently, the global search retrieves results from all data, which can be overwhelming and less efficient.

Improved Web Series Management:

Enhance the Web Series category by adding a "Next Episode" option in the player, which appears as the current episode ends.
Alternatively, display a list of all episodes within the player to allow users to select their desired episode seamlessly.
These updates would significantly enhance usability and user satisfaction.

**Comment by Fredolx** [comment]
might be considered for the mobile app. closing for now

**Comment by farhanffaa** [comment]
How to update, im not getting latest from window store

**Comment by Fredolx** [comment]
Microsoft is approving the update, you will get it probably in a few hours

**Comment by farhanffaa** [comment]
can you send me exe file or any link where I can download it, I'm excited
to try new version
