### ISSUE TITLE
[Feature Request] Option to Refresh Sources on Startup

### ISSUE THREAD

**Issue by ttx99** [Fredolx/open-tv#88]
option you can toggle if you want to refresh sources when app is opened.

**Comment by Fredolx** [comment]
That's a great idea, I should be able to make this happen for next update

**Comment by Fredolx** [comment]
The feature is here
https://github.com/Fredolx/open-tv/pull/91 (merged)
It will be available next version.

**Comment by Fredolx** [comment]
Added with 1.2.0
