### ISSUE TITLE
important issue (remove toggle for category)

### ISSUE THREAD

**Issue by farhanffaa** [Fredolx/open-tv#97]
Remove the toggle for the category and organize them into sections like other platforms: Movies, Live, and Series. Create dedicated search bars for each section. Currently, while your player is fast, it is not user-friendly and can be challenging to navigate, which may lead to losing users. Focus on making the UI more intuitive and easier to use. Refer to the screenshots for additional guidance.

![Screenshot_9](https://github.com/user-attachments/assets/002dc608-b43b-4261-9c4c-4649680f10ec)
![Screenshot_10](https://github.com/user-attachments/assets/497f28a4-1753-4d6f-87b5-b2dc880ee107)

**Comment by Fredolx** [comment]
might consider something like this for the mobile version. The desktop version will not have this.
